name: Sync AI Progress

on:
  push:
    paths:
      - 'progress/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync Progress
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add progress/
          git commit -m "Update AI progress" || echo "No changes to commit"
          git push
